spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_security_tutorial
    username: spring_security_tutorial
    password: spring_security_tutorial
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    edgareldy.springsecuritytutorial: DEBUG
