-- Initial schema for the tutorial's EER model: users <-> roles <-> permissions (RBAC),
-- plus per-user tokens (activation, password reset, JWT blacklist).
-- Flyway applies this migration once, in every environment (dev, test via Testcontainers,
-- prod), so the schema Hibernate validates against (spring.jpa.hibernate.ddl-auto=validate)
-- is always defined here rather than generated from entities.

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR(50) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    email           VARCHAR(100) NOT NULL UNIQUE,
    password        VARCHAR(255) NOT NULL,
    enabled         BOOLEAN NOT NULL DEFAULT FALSE,
    account_locked  BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE roles (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE permissions (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource VARCHAR(50) NOT NULL,
    action   VARCHAR(50) NOT NULL
);

CREATE TABLE role_user (
    user_id BIGINT NOT NULL REFERENCES users (id),
    role_id BIGINT NOT NULL REFERENCES roles (id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE role_permission (
    role_id       BIGINT NOT NULL REFERENCES roles (id),
    permission_id BIGINT NOT NULL REFERENCES permissions (id),
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE activation_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users (id),
    token        VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP NOT NULL,
    expires_at   TIMESTAMP,
    validated_at TIMESTAMP
);

CREATE INDEX idx_activation_tokens_user_id ON activation_tokens (user_id);

CREATE TABLE password_reset_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users (id),
    token       VARCHAR(255) NOT NULL,
    type        VARCHAR(255) NOT NULL,
    expiry_date TIMESTAMP NOT NULL
);

CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens (user_id);

CREATE TABLE blacklisted_tokens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL REFERENCES users (id),
    token           VARCHAR(768) NOT NULL,
    jti             VARCHAR(255) NOT NULL UNIQUE,
    blacklisted_at  TIMESTAMP,
    created_at      TIMESTAMP NOT NULL,
    expires_at      TIMESTAMP,
    validated_at    TIMESTAMP
);

CREATE INDEX idx_blacklisted_tokens_user_id ON blacklisted_tokens (user_id);
